name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3

    - name: Install OBS Studio
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg v4l-utils
        sudo add-apt-repository ppa:obsproject/obs-studio
        sudo apt-get update
        sudo apt-get install -y obs-studio
  
    - name: Preset Blank Image
      run: |
        manycam-cli --start --preset "Blank Image"

    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Generate Report
      run: |
        pip install coverage
        pip install -r requirements.txt
        coverage run -m unittest discover test
        coverage xml -i
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        verbose: true

    - name: Stop OBS Studio
      run: |
        killall obs