name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3

    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9

    - name: Generate Report
      run: |
        pip install coverage
        pip install -r requirements.txt
        coverage run -m unittest discover test
        coverage xml -i
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2